// eslint-disable-next-line import/prefer-default-export
export const GET_DOCTORS_PENDING = 'GETDOCTORSPENDING';
export const GET_DOCTORS_SUCCESS = 'GETDOCTORSSUCCESS';
export const GET_DOCTORS_ERROR = 'GETDOCTORSERROR';
export const GET_USER_APPOINTMENTS_PENDING = 'GETUSERAPPONTMENTPENDING';
export const GET_USER_APPOINTMENT_SUCCESS = 'GETUSERAPPOINTMENTSUCCESS';
export const GET_USERAPPOINTMENT_ERROR = 'GETUSERAPPOINTMENTERROR';
