const GETDOCTORSPENDING = "GETDOCTORSPENDING";
const GETDOCTORSUCCESS = "GETDOCTORSSUCCESS";
const GETDOCTORSERROR = "GETDOCTORSERROR";
const GETUSERAPPOINTMENTSPENDING = "GETUSERAPPONTMENTPENDING";
const GETUSERAPPOINTMENTSUCCESS = "GETUSERAPPOINTMENTSUCCESS";
const GETUSERAPPOINTMENTERROR = "GETUSERAPPOINTMENTERROR";