// eslint-disable-next-line import/prefer-default-export
export const GET_DOCTORS_PENDING = 'GET_DOCTORS_PENDING';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const GET_DOCTORS_ERROR = 'GET_DOCTORS_ERROR';
export const GET_USER_APPOINTMENTS_PENDING = 'GET_USER_APPOINTMENTS_PENDING';
export const GET_USER_APPOINTMENTS_SUCCESS = 'GET_USER_APPOINTMENTS_SUCCESS';
export const GET_USER_APPOINTMENTS_ERROR = 'GET_USER_APPOINTMENTS_ERROR';
export const CREATE_USER_APPOINTMENT_SUCCESS = 'CREATE_USER_APPOINTMENT_SUCCESS';
export const DELETE_USER_APPOINTMENT = 'DELETE_USER_APPOINTMENT';
